ALTER TABLE images
DROP
CONSTRAINT images_user_id_fkey;

ALTER TABLE qrtz_blob_triggers
DROP
CONSTRAINT qrtz_blob_triggers_sched_name_trigger_name_trigger_group_fkey;

ALTER TABLE qrtz_cron_triggers
DROP
CONSTRAINT qrtz_cron_triggers_sched_name_trigger_name_trigger_group_fkey;

ALTER TABLE qrtz_simple_triggers
DROP
CONSTRAINT qrtz_simple_triggers_sched_name_trigger_name_trigger_group_fkey;

ALTER TABLE qrtz_simprop_triggers
DROP
CONSTRAINT qrtz_simprop_triggers_sched_name_trigger_name_trigger_grou_fkey;

ALTER TABLE qrtz_triggers
DROP
CONSTRAINT qrtz_triggers_sched_name_job_name_job_group_fkey;

CREATE TABLE competitor_listings
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id              BIGINT                                  NOT NULL,
    platform                VARCHAR(50)                             NOT NULL,
    competitor_name         VARCHAR(255)                            NOT NULL,
    external_product_id     VARCHAR(255),
    seller_name             VARCHAR(255),
    product_url             VARCHAR(255)                            NOT NULL,
    alert_threshold_percent DECIMAL,
    last_regular_price      DECIMAL,
    last_sale_price         DECIMAL,
    last_effective_price    DECIMAL,
    last_in_stock           BOOLEAN,
    last_crawled_at         TIMESTAMP(6) WITHOUT TIME ZONE,
    last_crawl_status       VARCHAR(255),
    last_error              VARCHAR(255),
    active                  BOOLEAN,
    CONSTRAINT pk_competitor_listings PRIMARY KEY (id)
);

DROP TABLE images CASCADE;

DROP TABLE qrtz_blob_triggers CASCADE;

DROP TABLE qrtz_calendars CASCADE;

DROP TABLE qrtz_cron_triggers CASCADE;

DROP TABLE qrtz_fired_triggers CASCADE;

DROP TABLE qrtz_job_details CASCADE;

DROP TABLE qrtz_locks CASCADE;

DROP TABLE qrtz_paused_trigger_grps CASCADE;

DROP TABLE qrtz_scheduler_state CASCADE;

DROP TABLE qrtz_simple_triggers CASCADE;

DROP TABLE qrtz_simprop_triggers CASCADE;

DROP TABLE qrtz_triggers CASCADE;

DROP TABLE scraped_data CASCADE;